import Config

# Configure your database
#
# To use Supabase locally, set DATABASE_URL to your Supabase connection string, for example:
# postgresql://postgres:<password>@db.rztgovegfhguftbnwopd.supabase.co:5432/postgres
database_url =
  System.get_env("DATABASE_URL") ||
    "postgresql://postgres:postgres@localhost:5432/sciencecritic_dev"

database_uri = URI.parse(database_url)
database_host = database_uri.host || ""
database_query = URI.decode_query(database_uri.query || "")
ssl_query_value = String.downcase(database_query["ssl"] || "")
sslmode_query_value = String.downcase(database_query["sslmode"] || "")

# Postgrex expects `ssl: true`; Supabase/Postgres URLs often use libpq-style
# query params such as `?sslmode=require`, so translate and strip those keys.
database_url =
  case Map.drop(database_query, ["ssl", "sslmode"]) do
    sanitized_query when sanitized_query == database_query ->
      database_url

    sanitized_query when sanitized_query == %{} ->
      %{database_uri | query: nil} |> URI.to_string()

    sanitized_query ->
      %{database_uri | query: URI.encode_query(sanitized_query)} |> URI.to_string()
  end

database_ssl? =
  ssl_query_value in ["true", "1"] or
    sslmode_query_value in ["require", "verify-ca", "verify-full"]

database_ssl =
  case System.get_env("DATABASE_SSL") do
    value when value in ["true", "1"] ->
      true

    value when value in ["false", "0"] ->
      false

    _ ->
      database_ssl? or String.ends_with?(database_host, ".supabase.co") or
        String.ends_with?(database_host, ".supabase.com")
  end

database_ssl_verify =
  case System.get_env("DATABASE_SSL_VERIFY") do
    value when value in ["true", "1"] -> true
    value when value in ["false", "0"] -> false
    _ -> sslmode_query_value in ["verify-ca", "verify-full"]
  end

database_ssl_config =
  if database_ssl do
    ssl_opts = [verify: if(database_ssl_verify, do: :verify_peer, else: :verify_none)]

    if database_host != "" do
      Keyword.put(ssl_opts, :server_name_indication, String.to_charlist(database_host))
    else
      ssl_opts
    end
  else
    false
  end

maybe_ipv6 = if System.get_env("ECTO_IPV6") in ["true", "1"], do: [:inet6], else: []

config :sciencecritic, Sciencecritic.Repo,
  url: database_url,
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  ssl: database_ssl_config,
  socket_options: maybe_ipv6

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sciencecritic, SciencecriticWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "o+dcguGonGYk+2tSUADPI6TpH0mu4A+Wvm6W0SYqUL4Lo93QOlApbitKZ8LxEDxU",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sciencecritic, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sciencecritic, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :sciencecritic, SciencecriticWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/sciencecritic_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :sciencecritic, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
